import React, { useEffect, useState, useMemo } from "react";
import { useParams } from "react-router-dom";
import moment from "moment";
import { AnimatePresence, motion } from "framer-motion";
import {
  LuCircleAlert,
  LuListCollapse,
  LuSparkles,
  LuTarget,
} from "react-icons/lu";
import SpinnerLoader from "../../components/Loader/SpinnerLoader";
import { toast } from "react-hot-toast";
import DashboardLayout from "../../components/layouts/DashboardLayout";
import RoleInfoHeader from "./components/RoleInfoHeader";
import axiosInstance from "../../utils/axiosInstance";
import { API_PATHS } from "../../utils/apiPaths";
import QuestionCard from "../../components/Cards/QuestionCard";
import GapAnalysisPanel from "../../components/Cards/GapAnalysisPanel";
import Drawer from "../../components/Drawer";
import SkeletonLoader from "../../components/Loader/SkeletonLoader";
import AIResponsePreview from "./components/AIResponsePreview";

const CATEGORY_CONFIG = {
  coding: { label: "Coding", color: "violet" },
  "system-design": { label: "System Design", color: "sky" },
  behavioral: { label: "Behavioral", color: "rose" },
  general: { label: "General", color: "slate" },
};

const QuestionsSkeletonLoader = () => (
  <div className="space-y-4 mt-5">
    {[1, 2, 3, 4].map((i) => (
      <div
        key={i}
        className="animate-pulse bg-white rounded-lg p-5 shadow-sm border border-gray-100"
      >
        <div className="flex items-start gap-3.5">
          <div className="w-5 h-5 bg-gray-200 rounded shrink-0" />
          <div className="flex-1 space-y-2">
            <div className="h-4 bg-gray-200 rounded w-5/6" />
            <div className="h-3 bg-gray-100 rounded w-2/3" />
          </div>
          <div className="w-8 h-8 bg-gray-100 rounded shrink-0" />
        </div>
      </div>
    ))}
  </div>
);

const EmptyQuestions = ({ onGenerate, isLoading }) => (
  <div className="flex flex-col items-center justify-center py-20 text-center">
    <div className="w-16 h-16 rounded-full bg-amber-100 flex items-center justify-center mb-5">
      <LuSparkles className="text-amber-600" size={28} />
    </div>
    <h3 className="text-xl font-semibold text-slate-700 mb-2">
      No Questions Yet
    </h3>
    <p className="text-slate-500 max-w-sm mb-6 text-sm leading-relaxed">
      Generate your first batch of AI-powered interview questions tailored to
      this session's role and topics.
    </p>
    <button
      className="flex items-center gap-2 text-sm text-white font-medium bg-amber-600 px-6 py-2.5 rounded-lg hover:bg-amber-700 transition-colors cursor-pointer disabled:opacity-50"
      onClick={onGenerate}
      disabled={isLoading}
    >
      {isLoading ? <SpinnerLoader /> : <LuSparkles size={16} />}
      Generate Questions
    </button>
  </div>
);

const InterviewPrep = () => {
  const { sessionId } = useParams();

  const [sessionData, setSessionData] = useState(null);
  const [errorMsg, setErrorMsg] = useState("");
  const [isSessionLoading, setIsSessionLoading] = useState(true);

  const [openLeanMoreDrawer, setOpenLeanMoreDrawer] = useState(false);
  const [explanation, setExplanation] = useState(null);

  const [isLoading, setIsLoading] = useState(false);
  const [isUpdateLoader, setIsUpdateLoader] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const [activeCategory, setActiveCategory] = useState("all");
  const [gapAnalysis, setGapAnalysis] = useState(null);
  const [isGapLoading, setIsGapLoading] = useState(false);
  const [showGapPanel, setShowGapPanel] = useState(false);

  const fetchSessionDetailsById = async () => {
    setIsSessionLoading(true);
    try {
      const response = await axiosInstance.get(
        API_PATHS.SESSION.GET_ONE(sessionId),
      );

      if (response.data && response.data.session) {
        setSessionData(response.data.session);
        if (response.data.session.gapAnalysis?.readinessScore != null) {
          setGapAnalysis(response.data.session.gapAnalysis);
        }
      }
    } catch (error) {
      setErrorMsg("Failed to load session. Please try again.");
      console.error("Error:", error);
    } finally {
      setIsSessionLoading(false);
    }
  };

  const generateConceptExplanation = async (question) => {
    try {
      setErrorMsg("");
      setExplanation(null);

      setIsLoading(true);
      setOpenLeanMoreDrawer(true);

      const response = await axiosInstance.post(
        API_PATHS.AI.GENERATE_EXPLANATION,
        { question },
      );

      if (response.data) {
        setExplanation(response.data);
      }
    } catch (error) {
      setExplanation(null);
      setErrorMsg("Failed to generate explanation, Try again later");
      console.error("Error:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const toggleQuestionPinStatus = async (questionId) => {
    try {
      const response = await axiosInstance.post(
        API_PATHS.QUESTION.PIN(questionId),
      );

      if (response.data && response.data.question) {
        fetchSessionDetailsById();
      }
    } catch (error) {
      console.error("Error:", error);
    }
  };

  const generateAndAddQuestions = async ({ isInitial = false } = {}) => {
    try {
      setIsUpdateLoader(true);
      setErrorMsg("");

      const aiResponse = await axiosInstance.post(
        API_PATHS.AI.GENERATE_QUESTIONS,
        {
          role: sessionData?.role,
          experience: sessionData?.experience,
          topicsToFocus: sessionData?.topicsToFocus,
          numberOfQuestions: 10,
        },
      );

      const generatedQuestions = aiResponse.data;

      const response = await axiosInstance.post(
        API_PATHS.QUESTION.ADD_TO_SESSION,
        { sessionId, questions: generatedQuestions },
      );

      if (response.data) {
        toast.success(
          isInitial
            ? "Your interview questions are ready!"
            : "Added More Q&A!!"
        );
        fetchSessionDetailsById();
      }
    } catch (error) {
      if (error.response && error.response.data.message) {
        setErrorMsg(error.response.data.message);
      } else {
        setErrorMsg("Something went wrong. Please try again.");
      }
    } finally {
      setIsUpdateLoader(false);
    }
  };

  const analyzeGap = async () => {
    try {
      setIsGapLoading(true);
      setShowGapPanel(true);
      setErrorMsg("");

      const response = await axiosInstance.post(
        API_PATHS.AI.ANALYZE_GAP(sessionId),
      );

      if (response.data) {
        setGapAnalysis(response.data);
      }
    } catch (error) {
      setErrorMsg(
        "Failed to analyze gap. Make sure your profile has skills and experience filled in.",
      );
      console.error("Error:", error);
    } finally {
      setIsGapLoading(false);
    }
  };

  useEffect(() => {
    if (sessionId) {
      fetchSessionDetailsById();
    }
    return () => {};
  }, []);

  useEffect(() => {
    if (
      sessionData &&
      !isSessionLoading &&
      sessionData.questions?.length === 0 &&
      !isUpdateLoader &&
      !hasAutoGenerated
    ) {
      setHasAutoGenerated(true);
      generateAndAddQuestions({ isInitial: true });
    }
  }, [sessionData, isSessionLoading]);

  const pinnedCount =
    sessionData?.questions?.filter((q) => q?.isPinned)?.length || 0;

  const categoryCounts = useMemo(() => {
    const counts = {};
    sessionData?.questions?.forEach((q) => {
      //Question 1: cat = "coding"
      //counts["coding"] = (undefined || 0) + 1;
      //counts = { coding: 1 };
      //First time seeing a category: counts["coding"] is undefined, and undefined || 0 gives 0, so 0 + 1 = 1.
      //Second time: counts["coding"] is 1, and 1 || 0 gives 1, so 1 + 1 = 2.
      const cat = q.category || "general";
      counts[cat] = (counts[cat] || 0) + 1;
    });
    return counts;
  }, [sessionData?.questions]);

  const availableCategories = Object.keys(categoryCounts).filter(
    (cat) => categoryCounts[cat] > 0,
  );
  const showTabs = availableCategories.length > 1;

  const filteredQuestions = useMemo(() => {
    if (!sessionData?.questions) return [];
    if (activeCategory === "all") return sessionData.questions;
    return sessionData.questions.filter(
      (q) => (q.category || "general") === activeCategory,
    );
  }, [sessionData?.questions, activeCategory]);

  // sessionData.questions (raw data from API)
  //   │
  //   ├──▶ categoryCounts ──▶ { coding: 2, "system-design": 1, ... }
  //   │                              │
  //   │                              ▼
  //   │                        Tab buttons with counts: "Coding (2)"
  //   │
  //   │    activeCategory (which tab is clicked)
  //   │         │
  //   ├─────────┤
  //   │         │
  //   ▼         ▼
  // filteredQuestions ──▶ Only questions matching the selected tab
  //                         │
  //                         ▼
  //                   Rendered QuestionCards
  return (
    <DashboardLayout>
      {isSessionLoading ? (
        <>
          <div className="bg-amber-200 text-black">
            <div className="container mx-auto px-4 md:px-8">
              <div className="h-[200px] flex flex-col justify-center animate-pulse">
                <div className="h-8 bg-amber-300/50 rounded w-64 mb-3" />
                <div className="h-4 bg-amber-300/50 rounded w-48 mb-4" />
                <div className="flex gap-3">
                  <div className="h-6 bg-amber-300/50 rounded-full w-28" />
                  <div className="h-6 bg-amber-300/50 rounded-full w-20" />
                  <div className="h-6 bg-amber-300/50 rounded-full w-32" />
                </div>
              </div>
            </div>
          </div>
          <div className="container mx-auto pt-4 pb-4 px-4 md:px-8">
            <QuestionsSkeletonLoader />
          </div>
        </>
      ) : (
        <>
          <RoleInfoHeader
            role={sessionData?.role || ""}
            topicsToFocus={sessionData?.topicsToFocus || ""}
            experience={sessionData?.experience || "-"}
            questions={sessionData?.questions?.length || "-"}
            description={sessionData?.description || ""}
            lastUpdated={
              sessionData?.updatedAt
                ? moment(sessionData.updatedAt).format("Do MMM YYYY")
                : ""
            }
            pinnedCount={pinnedCount}
            onAnalyzeGap={analyzeGap}
            isGapLoading={isGapLoading}
            gapScore={gapAnalysis?.readinessScore}
          />

          <div className="container mx-auto pt-4 pb-4 px-4 md:px-8">
            {/* Gap Analysis Panel */}
            {showGapPanel && (
              <div className="mb-6">
                {isGapLoading ? (
                  <div className="bg-white rounded-2xl border border-amber-100 p-6">
                    <div className="animate-pulse flex items-center gap-6">
                      <div className="w-28 h-28 bg-gray-100 rounded-full shrink-0" />
                      <div className="flex-1 space-y-3">
                        <div className="h-5 bg-gray-200 rounded w-48" />
                        <div className="h-3 bg-gray-100 rounded w-72" />
                        <div className="h-3 bg-gray-100 rounded w-56" />
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="relative">
                    <button
                      className="absolute top-4 right-4 text-xs text-slate-400 hover:text-slate-600 cursor-pointer z-10"
                      onClick={() => setShowGapPanel(false)}
                    >
                      Hide
                    </button>
                    <GapAnalysisPanel data={gapAnalysis} />
                  </div>
                )}
              </div>
            )}

            {/* Show collapsed gap hint if analysis exists but panel is hidden */}
            {!showGapPanel && gapAnalysis && (
              <button
                className="mb-4 text-xs text-amber-600 hover:text-amber-700 cursor-pointer flex items-center gap-1.5"
                onClick={() => setShowGapPanel(true)}
              >
                <LuTarget size={14} />
                Show Gap Analysis ({gapAnalysis.readinessScore}% Ready)
              </button>
            )}

            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold text-black">
                Interview Q & A
              </h2>
              {sessionData?.questions?.length > 0 && (
                <p className="text-xs text-slate-500">
                  {sessionData.questions.length} question
                  {sessionData.questions.length !== 1 ? "s" : ""} &middot;{" "}
                  {pinnedCount} pinned
                </p>
              )}
            </div>

            {/* Category Tabs -- auto-hide when only one category */}
            {showTabs && sessionData?.questions?.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-3">
                <button
                  className={`text-xs font-medium px-3 py-1.5 rounded-full border transition-colors cursor-pointer ${
                    activeCategory === "all"
                      ? "bg-amber-600 text-white border-amber-600"
                      : "bg-white text-slate-600 border-slate-200 hover:border-slate-300"
                  }`}
                  onClick={() => setActiveCategory("all")}
                >
                  All ({sessionData.questions.length})
                </button>
                {availableCategories.map((cat) => {
                  const config =
                    CATEGORY_CONFIG[cat] || CATEGORY_CONFIG.general;
                  return (
                    <button
                      key={cat}
                      className={`text-xs font-medium px-3 py-1.5 rounded-full border transition-colors cursor-pointer ${
                        activeCategory === cat
                          ? "bg-amber-600 text-white border-amber-600"
                          : "bg-white text-slate-600 border-slate-200 hover:border-slate-300"
                      }`}
                      onClick={() => setActiveCategory(cat)}
                    >
                      {config.label} ({categoryCounts[cat]})
                    </button>
                  );
                })}
              </div>
            )}

            {errorMsg && !openLeanMoreDrawer && (
              <p className="flex gap-2 text-sm text-red-500 font-medium mt-3">
                <LuCircleAlert className="mt-0.5 shrink-0" /> {errorMsg}
              </p>
            )}

            {/* Empty state / auto-generating */}
            {!sessionData?.questions?.length && !isSessionLoading && (
              isUpdateLoader ? (
                <QuestionsSkeletonLoader />
              ) : (
                <EmptyQuestions
                  onGenerate={() => generateAndAddQuestions({ isInitial: true })}
                  isLoading={isUpdateLoader}
                />
              )
            )}

            {/* Questions list */}
            {filteredQuestions.length > 0 && (
              <div className="grid grid-cols-12 gap-4 mt-5 mb-10">
                <div
                  className={`col-span-12 ${
                    openLeanMoreDrawer ? "md:col-span-7" : "md:col-span-8"
                  }`}
                >
                  <AnimatePresence>
                    {filteredQuestions.map((data, index) => (
                      <motion.div
                        key={data._id || index}
                        initial={{ opacity: 0, y: -20 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, scale: 0.95 }}
                        transition={{
                          duration: 0.4,
                          type: "spring",
                          stiffness: 100,
                          delay: index * 0.1,
                          damping: 15,
                        }}
                        layout
                        layoutId={`question-${data._id || index}`}
                      >
                        <QuestionCard
                          question={data?.question}
                          answer={data?.answer}
                          onLearnMore={() =>
                            generateConceptExplanation(data.question)
                          }
                          isPinned={data?.isPinned}
                          onTogglePin={() => toggleQuestionPinStatus(data._id)}
                          category={data?.category}
                        />
                      </motion.div>
                    ))}
                  </AnimatePresence>

                  {/* Load More at the bottom */}
                  {activeCategory === "all" &&
                    !isLoading &&
                    sessionData?.questions?.length > 0 && (
                      <div className="flex items-center justify-center mt-5">
                        <button
                          className="flex items-center gap-3 text-sm text-white font-medium bg-black px-5 py-2 mr-2 rounded text-nowrap cursor-pointer hover:bg-gray-800 transition-colors disabled:opacity-50"
                          disabled={isLoading || isUpdateLoader}
                          onClick={() => generateAndAddQuestions()}
                        >
                          {isUpdateLoader ? (
                            <SpinnerLoader />
                          ) : (
                            <LuListCollapse className="text-lg" />
                          )}{" "}
                          Load More
                        </button>
                      </div>
                    )}
                </div>
              </div>
            )}

            {/* Empty filtered state */}
            {activeCategory !== "all" &&
              filteredQuestions.length === 0 &&
              sessionData?.questions?.length > 0 && (
                <div className="text-center py-12">
                  <p className="text-sm text-slate-400">
                    No{" "}
                    {CATEGORY_CONFIG[activeCategory]?.label || activeCategory}{" "}
                    questions in this session.
                  </p>
                </div>
              )}

            <Drawer
              isOpen={openLeanMoreDrawer}
              onClose={() => setOpenLeanMoreDrawer(false)}
              title={!isLoading && explanation?.title}
            >
              {errorMsg && (
                <p className="flex gap-2 text-sm text-amber-600 font-medium">
                  <LuCircleAlert className="mt-1" /> {errorMsg}
                </p>
              )}
              {isLoading && <SkeletonLoader />}
              {!isLoading && explanation && (
                <AIResponsePreview content={explanation?.explanation} />
              )}
            </Drawer>
          </div>
        </>
      )}
    </DashboardLayout>
  );
};

export default InterviewPrep;
